# Generated by Django 5.1.4 on 2024-12-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_id',
        ),
    ]
