# Generated by Django 5.1.4 on 2025-01-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
