# Generated by Django 5.1.4 on 2025-01-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
