# Generated by Django 5.1.4 on 2025-01-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
